select dbo.CTB_LANCAMENTO_ITEM.RATEIO_FILIAL AS FILIAL_RATEIO, 
dbo.CTB_LANCAMENTO.COD_FILIAL AS FILIAL_LANCAMENTO, 
dbo.CTB_LANCAMENTO.DATA_LANCAMENTO,
dbo.CTB_LANCAMENTO.LANCAMENTO, 
dbo.CTB_LANCAMENTO_ITEM.ITEM, 
dbo.CTB_LANCAMENTO_ITEM.LX_TIPO_LANCAMENTO 
from CTB_LANCAMENTO , CTB_LANCAMENTO_ITEM
where dbo.CTB_LANCAMENTO.LANCAMENTO = dbo.ctb_lancamento_item.lancamento 
and dbo.CTB_LANCAMENTO_ITEM.LX_TIPO_LANCAMENTO IN ('ITP','CMS') 
and dbo.ctb_lancamento_item.rateio_filial <> dbo.CTB_LANCAMENTO.COD_FILIAL
and dbo.CTB_LANCAMENTO.DATA_LANCAMENTO between '2023-09-01' and '2023-09-30'
