SELECT 
A.CODIGO_FILIAL, 
A.TICKET, 
A.CODIGO_CLIENTE, 
A.VALOR_PAGO,
A.TERMINAL,
A.VENDEDOR,
A.DATA_VENDA,
A.DATA_DIGITACAO

FROM LOJA_VENDA A
WHERE A.CODIGO_FILIAL IN ('000001','000015')
AND A.DATA_VENDA = '20231003'

ORDER BY A.DATA_DIGITACAO DESC

