/* CONSULTAR A PORTA DAS IMPRESSORAS NO 'VALOR ATUAL' - LINX POS */
SELECT *
FROM PARAMETROS_LOJA_TERMINAL
WHERE PARAMETRO = 'PORTA_IMPRESSORA_FISCAL'
AND CODIGO_FILIAL = '000001'

/* CONSULTAR O VALOR ATUAL DA FILIAL - LINX MANAGER */
SELECT *
FROM PARAMETROS_LOJA
WHERE PARAMETRO = 'PORTA_IMPRESSORA_FISCAL'
AND CODIGO_FILIAL = '000001'
