SELECT
A.NF_NUMERO AS "NOTA FISCAL",
A.CODIGO_FILIAL AS "CÓD. FILIAL",
A.CODIGO_CLIENTE AS "CÓD. CLIENTE",
A.EMISSAO AS "EMISSÃO",
A.CHAVE_NFE AS "CHAVE NFE",
A.PROTOCOLO_AUTORIZACAO_NFE AS "PROTOCOLO NFE",
A.DATA_AUTORIZACAO_NFE AS "DATA AUTORIZAÇÃO",
A.STATUS_NFE AS "STATUS NFE",
A.LOG_STATUS_NFE AS "LOG NFE"


FROM LOJA_NOTA_FISCAL A

WHERE A.NOTA_CANCELADA = '0'
AND A.STATUS_NFE IN ('4', '2')
AND A.NF_NUMERO NOT IN ('000005108')
AND A.CODIGO_FILIAL IN ('000001','000015')

ORDER BY A.EMISSAO