/* CONSULTAR A PORTA DAS IMPRESSORAS NO 'VALOR ATUAL' - LINX POS */
SELECT *
FROM PARAMETROS_LOJA_TERMINAL
WHERE PARAMETRO IN ('IMPRESSORA_NF', 'IMPRESSORA_NFCE', 'IMPRESSORA_TICKET')
AND CODIGO_FILIAL = '000001'
AND TERMINAL IN ('001', '002', '003')

ORDER BY TERMINAL ASC

/* CONSULTAR O VALOR ATUAL DA FILIAL - LINX MANAGER */
SELECT *
FROM PARAMETROS_LOJA
WHERE PARAMETRO IN ('IMPRESSORA_NF', 'IMPRESSORA_NFCE', 'IMPRESSORA_TICKET')
AND CODIGO_FILIAL = '000001'

