Select a.t$ccnt as "Contato",
       a.t$bpid as "Parceiro",
       b.t$nama as "Razão social",
       b.t$fovn$l as "Entidade",
       b.t$cste as "Estado",
       a.t$fuln as "Nome completo",
       a.t$ddd1$c as DDD,
       a.t$telp as "Telefone",
       a.t$info as "E-mail",
       a.t$crus as "Cod.Criado por",
       g.t$name as "Criado por",
       TO_CHAR(a.t$crdt, 'DD/MM/YYYY') AS "Data criação",
       e.t$repr$c as "Cod. representante",
       f.t$dsca as "Representante",
       
       decode(e.t$repr$c,
              'R00035',
              'Sul',
			  'R00038',
	          'Sul',	
              'R00158',
              'Sul',
              'R00159',
              'Sul',
              'R00038',
              'Sul',
              'R00126',
              'Sul',
              'R00036',
              'Sul',
              'R00032',
              'Sul',
              'R00129',
              'Sul',
              'R00203',
              'Sul',
              'R00201',
              'Sul',
              'R00040',
              'Sul',
              'R00072',
              'Sul',
              'R00041',
              'Sul',
              'R00195',
              'Sul',
              'R00165',
              'Sul',
              'R00048',
              'Sul',
              'R00229',
              'Sul',
              'R00219',
              'Sul',
			  'R00236',
			  'Sul',
			  'R00232',
			  'Sul',
			  'R00253',
			  'Sul',
			  'R00149',
              'Centro',
              'R00223',
              'Centro',
              'R00050',
              'Centro',
              'R00225',
              'Centro',
              'R00226',
              'Centro',
              'R00198',
              'Centro',
              'R00077',
              'Centro',
              'R00199',
              'Centro',
              'R00197',
              'Centro',
              'R00215',
              'Centro',
              'R00205',
              'Centro',
              'R00210',
              'Centro',
              'R00211',
              'Centro',
              'R00087',
              'Centro',
              'R00163',
              'Centro',
              'R00216',
              'Centro',
              'R00214',
              'Centro',
              'R00103',
              'Centro',
			  'R00260',
			  'Centro',
			  'R00234',
			  'Centro',
			  'R00239',
			  'Centro',
			  'R00250',
			  'Centro',
              'R00051',
              'Norte/Nordeste',
              'R00092',
              'Norte/Nordeste',
              'R00133',
              'Norte/Nordeste',
              'R00193',
              'Norte/Nordeste',
              'R00140',
              'Norte/Nordeste',
              'R00012',
              'Norte/Nordeste',
              'R00120',
              'Norte/Nordeste',
              'R00206',
              'Norte/Nordeste',
              'R00123',
              'Norte/Nordeste',
              'R00013',
              'Norte/Nordeste',
              'R00227',
              'Norte/Nordeste',
              'R00213',
              'Norte/Nordeste',
              'R00209',
              'Norte/Nordeste',
			  'R00242',
			  'Norte/Nordeste',
			  'R00123',
			  'Norte/Nordeste',
			  'R00262',
			  'Norte/Nordeste',
			  'R00263',
			  'Norte/Nordeste',
			  'R00261',
			  'Norte/Nordeste',
			  'R00247',
			  'Norte/Nordeste',
			  'R00266',
			  'Norte/Nordeste',
			  'R00124',
			  'Norte/Nordeste',
              'R00078',
              'São Paulo',
              'R00118',
              'São Paulo',
              'R00208',
              'São Paulo',
              'R00003',
              'São Paulo',
              'R00202',
              'São Paulo',
              'R00095',
              'São Paulo',
              'R00188',
              'São Paulo',
              'R00192',
              'São Paulo',
              'R00134',
              'São Paulo',
              'R00112',
              'São Paulo',
              'R00191',
              'São Paulo',
              'R00186',
              'São Paulo',
              'R00224',
              'São Paulo',
              'R00111',
              'São Paulo',
			  'R00048',
              'São Paulo',
			  'R00073',
              'São Paulo',
			  'R00267',
              'São Paulo',
              'R00204',
              'Brás',
              'R00060',
              'Brás',
              'R00058',
              'Sul',
              'R00060',
              'São Paulo',
              'R00061',
              'Centro Norte',
              'R00062',
              'Nordeste',
              'R00064',
              'Exportação',
              'R00145',
              'SP Interior',
              'R00059',
              'Sudeste',
              'R00184',
              'Key Account',
              'R00079',
              'Key Account',
              'R00063',
              'Direto',
              'R99999',
              'Direto',
              'R00127',
              'Direto',
              'R99996',
              'Direto',
              'R00196',
              'PL',
              'R00056',
              'Exportação',
              'R00136',
              'Exportação',
              ' ',
              'Sem informação') as "Regional"

  From igrppr.ttccom140001 a, /*Contatos*/
       igrppr.ttccom130001 b, /*Endereços*/
       igrppr.ttccom110001 c, /*Parceiros de negócios clientes*/
       igrppr.ttccom100001 d, /*Parceiros de negócios*/
       igrppr.ttdzbr003001 e, /*Cadastro de Atendimento aos Clientes*/
       igrppr.ttcmcs065001 f, /*Departamentos*/
       igrppr.tttaad200000 g /*Dados do usuário*/

 where a.t$bpid = c.t$ofbp
   and c.t$ofbp = d.t$bpid
   and a.t$wadr = b.t$cadr
   and c.t$cadr = d.t$cadr
   and f.t$cwoc = e.t$repr$c
   and e.t$bpid$c = d.t$bpid
   and a.t$crus = g.t$user
   and e.t$ativ$c = '1' /*Representante Ativo*/
   and e.t$styp$C = '002' /*Confecção*/
   And d.t$ctit = '001' /*Buscar apenas clientes*/
   And a.t$ccnt like 'C%' /*Inicial Contato*/
   and b.t$ccty = 'BRA'
   and a.t$crdt BETWEEN (SELECT SYSDATE FROM DUAL) - 7 AND
       (SELECT SYSDATE FROM DUAL) - 1 /*Busca semana anterior*/

 order by a.t$bpid /*Ordenar pelo B do Parceiro*/

/* By Ferreira */
 
/* Atualizado: 15/08/2023 | Ajuste no formato da data / Adicionado o campo representante / Regionais puxando pelo representante */
/* Atualizado: 02/12/2024 | Atualização na busca de novos representantes */ 
 
